version: '3.4'
services:
  cassandra:
    image: cassandra:3.11.7
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - ./out/cassandra_data:/var/lib/cassandra
  load-cassandra:
    container_name: load_cassandra
    environment:
      WAIT_HOSTS: cassandra:9042
    build:
      dockerfile: Dockerfile-load-cassandra
      context: .
    depends_on:
      - cassandra
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4567-4584:4567-4584"
      - "8055:8888"
    environment:
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3:4572
      - DEFAULT_REGION=us-east-1
      - LOCALSTACK_HOSTNAME=localstack
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/private${TMPDIR}:/tmp/localstack"
  setup-resources:
    container_name: awscli
    image: mesosphere/aws-cli
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/private${TMPDIR}:/tmp/localstack"
    environment:
      - AWS_ACCESS_KEY_ID=dummyaccess
      - AWS_SECRET_ACCESS_KEY=dummysecret
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    entrypoint: /bin/sh -c
    command: >
      "
        sleep 10;
        aws --endpoint-url=http://localstack:4572 s3 mb s3://demo-bucket
      "
    depends_on:
      - localstack